
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


# (APPENDIX) 付録 {-}

# 参考資料

## 文献

### 統計学の解説書  
* 東京大学教養学部統計学教室 編 (1991). 統計学入門 東京大学出版会  
* 南風原朝和 (2002). 心理統計学の基礎：統合的理解のために 有斐閣  
* 大久保街亜・岡田謙介 (2012). 伝えるための心理統計：効果量・信頼区間・検定力 勁草書房

### Rを用いた統計解析の解説書
* 山田剛史・杉澤武俊・村井潤一郎 (2008). Rによるやさしい統計学 オーム社  
* 石田基広 監修，奥村晴彦 (2016). Rで楽しむ統計　共立出版  
* 金明哲　(2016). 定性的データ分析（Useful R 5） 共立出版  
* 嶋田正和・阿部真人 (2017). Rで学ぶ統計学入門　東京化学同人  

  
### 一般化線形モデル，マルチレベルモデルなどの解説書  
* 久保拓哉 (2012). データ解析のための統計モデリング入門：一般化線形モデル・階層ベイズモデル・MCMC　岩波書店  
* 金明哲 編，粕谷英一　(2012). 一般化線形モデル（Rで学ぶデータサイエンス 10） 共立出版  

### ベイズ統計モデリングの解説書  
* 石田基広 監修，松浦健太郎 (2016). StanとRでベイズ統計モデリング　共立出版  
* 馬場真哉 (2019). RとStanではじめるベイズ統計モデリングによるデータ分析入門（実践Data Science シリーズ） 講談社  
* McElrearth R. (2020). Statistical Rethinking: A Bayesian Course with Examples in R and Stan (2nd Ed.) Boca Raton, FL: CRC Press  


## Webサイト


RStudio Cheatsheets（代表的なパッケージの使い方などが簡単にまとめられた”チートシート”を入手できる）  
[https://rstudio.com/resources/cheatsheets/](https://rstudio.com/resources/cheatsheets/)  
  
`tidyverse`の公式ページ  
[https://www.tidyverse.org](https://www.tidyverse.org)  
  
Stan User's Guide  
[https://mc-stan.org/users/documentation/](https://mc-stan.org/users/documentation/)  



# R Markdownの使い方

