---
title: "CV"
---

# **Education**

Hokkaido University, M.A. (Behavioral Science)  

Hokkaido University, Ph. D. (Behavioral Science)

# **Professional experiences**

Associate professor, Teikyo University, 2019-

Assistant professor, Teikyo University, 2016-2019

Project assistant professor, National Institute of informatics of Japan, 2013-2016

Post-doctoral research fellow, Department of Behavioral Sciences, Hokkaido University, the Japanese Society for the Promotion of Science 2012-2013

Post-doctoral research fellow, Department of Psychology, Sophia University, the Japanese Society for the Promotion of Science, 2011-2012

# **Publications**

### **Journal of Articles**

\*Correspondence author

-   **Horita, Y.**\*, & Yamazaki, M. (2025). Generalized trust rather than perception of relational mobility correlates with nominating close friends in a social network. *Japanese Psychological Research*, *67*(2), 272–283. <https://doi.org/10.1111/jpr.12451>

-   **Horita, Y.**\*, Yamazaki, M., & Tahara, A. (2025). Relational mobility is associated with generalized rust but not intimacy: A survey of individuals from the U.S. and Japan. *Asian Journal of Social Psychology*, *28*(3), e70027. [https://doi.org/10.1111/ajsp.70027](#0)

-   **Horita, Y.**\*, & Kawada, K. (2025). Evaluations of dominant leadership in workplaces are associated with paranoia. *Letters on Evolutionary Behavioral Science*, *16*(1), 1–7. [https://doi.org/10.5178/lebs.2025.123](#0)

-   **Horita, Y**.\*, & Hamada, S. (2024). Revisiting the bounded generalized reciprocity model: Ingroup favoritism and concerns about negative evaluation. *Journal of Experimental Social Psychology*, *113*, 104618. [https://doi.org/10.1016/j.jesp.2024.104618](#0 "Persistent link using digital object identifier")

-   **Horita, Y.**\* (2023). Paranoid thinking and perceived competitive intention. *PeerJ*, *11*, e15003. <https://doi.org/10.7717/peerj.15003>

-   [**Horita, Y.**]{.underline}\* (2021). Conjecturing harmful intent and preemptive strike in paranoia. *Frontiers in Psychology*, *12*, 726081. <https://doi.org/10.3389/fpsyg.2021.726081>

-   **Horita, Y.**\* (2020). Greater effects of mutual cooperation and defection on subsequent cooperation in direct reciprocity games than generalized reciprocity games: Behavioral experiments and analysis using multilevel models. *PLOS ONE*, *15*, e0242607. <https://doi.org/10.1371/journal.pone.0242607>

-   **Horita, Y.**\*, & Takezawa, M. (2018). Cultural differences in strength of conformity explained through pathogen stress: a statistical test using hierarchical Bayesian estimation. *Frontiers in Psychology*, *9*, 1921. <https://doi.org/10.3389/fpsyg.2018.01921>

-   **Horita, Y.**, Takezawa, M., Inukai, K., Kita, T., & Masuda, N.\* (2017). Reinforcement learning accounts for moody conditional cooperation behavior: experimental results. *Scientific Reports*, *7*, 39275. <https://doi.org/10.1038/srep39275>

-   Ezaki, T., **Horita, Y.**, Takezawa, M., & Masuda N.\* (2016). Reinforcement learning explains conditional cooperation and its moody cousin. *PLoS Computational Biology*, *12*, e1005034. <https://doi.org/10.1371/journal.pcbi.1005034>

-   **Horita, Y.**, Takezawa, M., Kinjo, T., Nakawake, Y., & Masuda, N.\* (2016). Transient nature of cooperation by pay-it-forward reciprocity. *Scientific Reports*, *6*, 19471. <https://doi.org/10.1038/srep19471>

-   **Horita, Y.**, & Takezawa, M.\* (2014). Observation enhances third-party punishment only among people who were not hot-tempered. *Letters on Evolutionary Behavioral Science*, *5*, 5-8. [https://doi.org/10.5178/lebs.2014.28](#0)

-   Yamagishi, T.\*, Mifune, N., Li, Y., Shinada, M., Hashimoto, H., **Horita, Y.***,* Miura, A., Inukai, K., Tanida, S., Kiyonari, T., Takagishi, H., & Simunovic, D. (2013). Is behavioral pro-sociality game-specific? Pro-social preference and expectations of pro-sociality. *Organizational Behavior and Human Decision Processes*, *120*, 260-271. [https://doi.org/10.1016/j.obhdp.2012.06.002](#0)

-   Yamagishi, T.\*, **Horita, Y.**, Mifune, N., Hashimoto, H., Li, Y., Shinada, M., Miura, A., Inukai, K., Takagishi, H., & Simunovic, D. (2012). Rejection of unfair offers in the ultimatum game is no evidence of strong reciprocity. *Proceedings of the National Academy of Sciences of the United States of America*, *109*, 20364-20368. <https://doi.org/10.1073/pnas.1212126109>

-   Yamagishi, T.\*, Hashimoto, H., Cook, K., Kiyonari, T., Shinada, M., Inukai, K., Takagishi, H., **Horita, Y.**, & Li, Y. (2012). Modesty in Self-presentation: A comparison between the U.S. and Japan. *Asian Journal of Social Psychology*, *15*, 60-68. [https://doi.org/10.1111/j.1467-839X.2011.01362.x](#0)

-   Takahashi, T.\*, Shinada, M., Inukai, K., Tanida, S., Takahashi, C., Mifune, N., Takagishi, H., **Horita, Y.**, Hashimoto, H., Yokota, K., Kameda, T., & Yamagishi, T. (2010). Stress hormones predict hyperbolic time-discount rates six months later in adults. *Neuroendocrinology Letters*, *31*, 616-621.

-   Inukai, K., Shinada, M., Tanida, S., Takahashi, C., Mifune, N., Takagishi, H., **Horita, Y.**, Hashimoto, H., Yokota, K., Kameda, T., Yamagishi, T., & Takahashi, T.\* (2010). Salivary alpha-amylase levels and big five personality factors in adults. *Neuroendocrinology Letters*, *31*, 771-774.

-   Takagishi, H., Takahashi, T.\*, Yamagishi, T., Shinada, M., Inukai, K., Tanida, S., Mifune, N., **Horita, Y.**, Hashimoto, H., L, Y., Yokota, K., Kameda, T., & Yamagishi, T. (2010). Salivary testosterone levels and autism-spectrum quotient in adults. *Neuroendocrinology Letters*,*31*, 837-841.

-   **Horita, Y.**\* (2010). Punishers may be chosen as resource providers but not as recipients. *Letters on Evolutionary Behavioral Science*, *1*, 6-9. [https://doi.org/10.5178/lebs.2010.2](#0)

-   Schug, J., Matsumoto, D., **Horita, Y.**, Yamagishi, T.\*, & Bonnet, K. (2010). Emotional expressivity as a signal of cooperation. *Evolution and Human Behavior*, *31*, 87-94. <https://doi.org/10.1016/j.evolhumbehav.2009.09.006>

-   Yamagishi, T.\*, **Horita, Y.**, Takagishi, H., Shinada, M., Tanida, S., & Cook, K. S. (2009) The private rejection of unfair offers and emotional commitment. *Proceedings of the National Academy of Sciences of the United States of America*, *106*, 11520-11523. [https://doi.org/10.1073/pnas.0900636106](#0)

# **Grants**

-   Grants-in-Aids for the Japanese Research: Scientific Research (C), 2021-2024

-   Grants-in-Aids for the Japanese Research: Young Scientists, 2018-2020

-   Grants-in-Aids for the Japanese Research: Young Scientists (B), 2015-2017

# **Academic activities**

## Scientific committee

2022– Human Behavior and Evolution Society Japan, Auditor

2021 Cultural Evolution Society Conference 2021 Sapporo, Local Committee member

## Editorial board

2023– PLOS ONE, Editorial board member

2019– Letters on Evolutionary Behavioral Science, Editorial board member

## Ad hoc journal reviewer 

*Asian Journal of Social Psychology, BMC Psychology, Communications Psychology, Computational Cognitive Science, Current Psychology, Economics Bulletin, Evolutionary Behavioral Sciences, Evolutionary Psychology, Frontiers in Behavioral Neuroscience, Frontiers in Psychology, International Journal of Psychology, Japanese Psychological Research, Journal of Behavioral Decision Making, Journal of Cognitive Psychology, Journal of Economic Psychology, Journal of Experimental Psychology: Applied, Journal of Experimental Social Psychology, Letters on Evolutionary Behavioral Science, PLOS ONE, Proceedings of Royal Society: B, Review of Behavioral Economics, Scientific Reports, Social Psychology Quarterly*
