---
title: "心理データ応用解析法"
author: "帝京大学文学部心理学科　堀田結孝"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
#output: word_document
output: 
  bookdown::gitbook:
    split_by: rmd
---



```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# はじめに {#introduction}

このテキストでは、Rを使いながら心理学における応用的なデータ解析を学んでいく。    
  
心理学を専攻していて基礎統計学を学修済みの学生を対象としている。また、Rを全く使ったことがない人も想定して、Rのインストールの仕方から基本的な使い方も解説する。  
  
このテキストでは、t検定や分散分析など心理統計で学んだ手法を**統計モデル**という一つの枠組みで包括的に理解することを目的とする。具体的には**線形モデル**、**一般化線形モデル**、**マルチレベルモデル**を順に学んでいき、様々な種類のデータに対して柔軟に解析を行う技術を身に着けていく。  
  

## テキストの構成
  
このテキストでは、R及びRStudioを用いてデータ解析の練習をしていく。  
  
第2章から第5章にかけては、Rの使い方について扱っている。  
  
第2章ではRのインストール、Rでのプログラムの書き方、パッケージのインストールの仕方など、Rを使ってデータ解析をする上で基本的なことについて、初めてRを使う人向けに解説している。第3章では、平均値や標準偏差、相関などの基礎統計量をRで計算する方法について解説する。第4章と第5章では、Rでデータを加工する方法やグラフの作成などについて解説する。  
  
第6章以降で、データ解析について学んでいく。  
  
まずは、心理統計でも学んだ内容の復習も交え、統計モデルを用いる上で必要な知識を順に学んでいく。第6章では、**確率分布**について学ぶ。第7章では、**統計的仮説検定**とそれが抱える問題を学ぶ。第8章では、t検定、χ二乗検定など、心理統計で学んだ解析をRで行う方法について解説する。       
  
第9章からは、統計モデルについて学んでいく。第9章では**線形モデル**を学ぶ。この章では、心理統計における回帰分析の復習を通して、t検定、分散分析などの解析法が線形モデルという一つの枠組みで扱えることを学んでいく。第10章では、線形モデルで解析を行う上での注意点について触れる。  
  
第11章と第12章では、線形モデルの拡張である**一般化線形モデル**を学ぶ。質的変数など、正規分布に従わないデータを解析する手法を学んでいく。第11章では代表的な解析法としてロジスティック回帰とポアソン回帰について、第12章ではその他の一般化線形モデルについて学ぶ。一般化線形モデルを用いることで、様々な種類のデータに対して柔軟な解析が可能となることを理解していく。  
  
第13章では、更に一般化線形モデルを拡張させた**マルチレベルモデル**を学ぶ。同じ集団や個人から得られたデータなど、個人差や集団差を含むデータを解析する手法について学ぶ。  

第14章と第15章にかけては、ベイズ統計など、より応用的な解析について学ぶ。

### テキストの読み方

各章の最後に、確認問題を設ける。  
  
