---
title: "研究内容"
---

**関連領域：社会心理学，行動経済学，進化心理学，文化心理学**

**キーワード**：協力，信頼，罰，社会的ジレンマ，評判，集団，文化，社会的ネットワーク

他の動物とは異なり，人間は他者と協力しあい，大規模で複雑な社会を形成しています。人間の社会や文化の形成に果たす行動の背後にある心理メカニズム及び進化・適応的基盤について，実験研究などの手法を用いて研究しています。

## **1. 利他行動の心理メカニズム**

利他行動（他者を助ける行動）や規範逸脱者に対する罰行動の背後にある心理メカニズムについて，実験研究等を通して検討しています。

キーワード：利他行動，互恵性，罰，感情

関連研究

-   Schug, J., Matsumoto, D., Horita, Y., Yamagishi, T., & Bonnet, K. (2010). Emotional expressivity as a signal of cooperation. *Evolution and Human Behavior*, *31*, 87-94. <https://doi.org/10.1016/j.evolhumbehav.2009.09.006> 

-   Yamagishi, T., Horita, Y., Takagishi, H., Shinada, M., Tanida, S., & Cook, K. S. (2009) The private rejection of unfair offers and emotional commitment. *Proceedings of the National Academy of Sciences of the United States of America*, *106*, 11520-11523. <https://doi.org/10.1073/pnas.0900636106>

-   堀田結孝・山岸俊男 (2008). 最後通告ゲームでの意図のない不公正分配の拒否　実験社会心理学研究, *47*, 169-177. <https://doi.org/10.2130/jjesp.47.169>

-   堀田結孝・山岸俊男 (2007). 互酬性と同一性保護――最後通告ゲームにおける拒否の理由――　心理学研究, *78*, 446-451. <https://doi.org/10.4992/jjpsy.78.446>

## **2. 協力を支える制度**

大規模な協力関係を維持させるために，共同体のメンバー同士で持続可能な制度の仕組みについて関心があります。主に，罰や評判の役割に注目しています。 

キーワード：罰，評判，社会的交換

関連研究

-   Horita, Y., Takezawa, M., Kinjo, T., Nakawake, Y., & Masuda, N. (2016). Transient nature of cooperation by pay-it-forward reciprocity. *Scientific Reports*, *6*, 19471. <https://doi.org/10.1038/srep19471>

-   Horita, Y., & Takezawa, M. (2014). Observation enhances third-party punishment only among people who were not hot-tempered. *Letters on Evolutionary Behavioral Science*, *5*, 5-8. <https://doi.org/10.5178/lebs.2014.28>

-   波多野礼佳・堀田結孝・山岸俊男 (2013). 他者意見が罰行動に与える影響 　心理学研究, *83*, 582-588. <https://doi.org/10.4992/jjpsy.83.582>

-   Horita, Y. (2010). Punishers may be chosen as resource providers but not as recipients. *Letters on Evolutionary Behavioral Science*, *1*, 6-9. <https://doi.org/10.5178/lebs.2010.2> 

## **3. 心理傾向の文化的多様性**

文化進化の観点（社会的学習や規範などの影響）から，集団志向的な心理傾向などの文化的多様性はどのようなプロセスを通して形成されるのかについて興味を持っています。  

キーワード：比較文化，文化進化

関連研究

-   Horita, Y., & Takezawa, M. (2018). Cultural differences in strength of conformity explained through pathogen stress: a statistical test using hierarchical Bayesian estimation. *Frontiers in Psychology*, *9*, 1921. <https://doi.org/10.3389/fpsyg.2018.01921> 

## **4. 社会的ネットワークと関わる心理メカニズム**

社会的ネットワーク（他者とのつながり）の形成や維持などに関わる心理メカニズムについて、社会環境への適応の観点から検討しています。   

キーワード：信頼, 社会的ネットワーク 

関連研究

-   Horita, Y., & Yamazaki, M. (2023). Generalized trust rather than perception of relational mobility correlates with nominating close friends in a social network. *Japanese Psychological Research*, <https://doi.org/10.1111/jpr.12451>
-   Horita, Y., Yamazaki, M., & Tahara, A. (2025). Relational mobility is associated with generalized rust but not intimacy: A survey of individuals from the U.S. and Japan. *Asian Journal of Social Psychology*, *28*(3), e70027. <https://doi.org/10.1111/ajsp.70027> 

## **5. ネガティブな心理傾向への進化心理学的アプローチ** 

他者に対する不信感のようなネガティブな思考が，いつ，どのようなときに生じ得るのかについて，進化心理学的観点から検討しています。    

キーワード：不信頼，進化心理学的アプローチ 

関連研究

-   Horita, Y., & Kawada, K. (2025). Evaluations of dominant leadership in workplaces are associated with paranoia. *Letters on Evolutionary Behavioral Science*, *16*(1), 1–7. <https://doi.org/10.5178/lebs.2025.123>

-   Horita, Y. (2023). Paranoid thinking and perceived competitive intention. *PeerJ*, 11, e15003. <https://doi.org/10.7717/peerj.15003>

-   Horita, Y. (2021). Conjecturing harmful intent and preemptive strike in paranoia. *Frontiers in Psychology*, *12*, 726081. <https://doi.org/10.3389/fpsyg.2021.726081>

## **6. 集団に基づく協力**  

集団を区別した協力行動の背後にある心理メカニズムと進化的基盤について検討しています。 

キーワード：内集団バイアス，評判 

関連研究

-   Horita, Y., & Hamada, S. (2024). Revisiting the bounded generalized reciprocity model: Ingroup favoritism and concerns about negative evaluation. *Journal of Experimental Social Psychology*, *113*, 104618. <https://doi.org/10.1016/j.jesp.2024.104618>

-   堀田結孝・山岸俊男 (2010). 集団内における互恵性の適応基盤 心理学研究，*81*, 114-122. <https://doi.org/10.4992/jjpsy.81.114> 
